GET http://localhost:8080/itsystem/api/documents/issues?email=nehemiasbelong@gmail.com HTTP/1:1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuZWhlbWlhc2JlbG9uZ0BnbWFpbC5jb20iLCJleHAiOjE2MDUwNjk4MDJ9.MpmBAHmi8Op4rPzvVEv1oUU8FpcpMXZJnHmTbxkxPGpjWtbn-5vOfqqhuM9cvAm965dzyV9e5x8BnedSNiXjrA

